# Generated by Django 6.0.1 on 2026-01-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_documentcategory_added_by_documentcategory_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='version_number',
            field=models.CharField(max_length=20),
        ),
    ]
