# Generated by Django 6.0.1 on 2026-01-26 17:46

import dms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_documenttype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to=dms.models.DocumentVersion._upload_to),
        ),
    ]
