# Generated by Django 6.0.1 on 2026-01-12 11:41

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[core.validators.validate_logo]),
        ),
    ]
