# Generated by Django 6.0.1 on 2026-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunitmodule',
            name='module_type',
            field=models.CharField(choices=[('DMS', 'Document Management'), ('IR', 'Incident Reporting'), ('NC', 'Non Conformance'), ('TRN', 'Training & Learning')], max_length=10),
        ),
    ]
