# Generated by Django 6.0.1 on 2026-01-11 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BU_ADMIN', 'Business Unit Admin'), ('QUALITY', 'Quality Officer'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'business_unit')},
            },
        ),
    ]
