# Generated by Codex on 2026-04-11
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_quality_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunitmembership',
            name='role',
            field=models.CharField(
                choices=[
                    ('BU_ADMIN', 'Business Unit Admin'),
                    ('QUALITY_MANAGER', 'Quality Manager'),
                    ('QUALITY_LEAD', 'Quality Lead'),
                    ('QUALITY', 'Quality Officer'),
                    ('TRAINING_ADMIN', 'Training Admin'),
                    ('TRAINING_OFFICER', 'Training Officer'),
                    ('LINE_MANAGER', 'Line Manager'),
                    ('EMPLOYEE', 'Employee'),
                    ('STAFF', 'Staff'),
                ],
                default='STAFF',
                max_length=20,
            ),
        ),
    ]
