# Generated by Django 6.0.1 on 2026-04-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0002_nc_settings_and_workflow'),
        ('nc', '0002_nonconformance_reference_per_bu'),
    ]

    operations = [
    ]
