# Generated by Django 6.0.1 on 2026-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Reviewed', 'Reviewed'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
