from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_categories', to='core.businessunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={'unique_together': {('business_unit', 'name')}},
        ),
        migrations.CreateModel(
            name='TrainingVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_vendors', to='core.businessunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={'unique_together': {('business_unit', 'name')}},
        ),
        migrations.CreateModel(
            name='TrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('PDF', 'PDF'), ('PPT', 'PowerPoint'), ('SCORM', 'SCORM'), ('VIDEO', 'Video'), ('ASSESSMENT', 'Assessment'), ('COVER', 'Cover Page')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='training/library/')),
                ('external_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_contents', to='core.businessunit')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_training_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('publish_start_date', models.DateField()),
                ('publish_end_date', models.DateField(blank=True, null=True)),
                ('course_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('min_effort_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_effort_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='training/courses/covers/')),
                ('trailer_video', models.FileField(blank=True, null=True, upload_to='training/courses/trailers/')),
                ('mandatory_enabled', models.BooleanField(default=False)),
                ('validity_years', models.PositiveIntegerField(default=1)),
                ('delivery_type', models.CharField(choices=[('INHOUSE', 'In-house'), ('VENDOR', 'Vendor')], default='INHOUSE', max_length=20)),
                ('accreditation_enabled', models.BooleanField(default=False)),
                ('accreditation_number', models.CharField(blank=True, max_length=100)),
                ('accreditation_body', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_courses', to='core.businessunit')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='training.trainingcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_courses', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='training.trainingvendor')),
            ],
            options={'ordering': ['-publish_start_date', 'title']},
        ),
        migrations.CreateModel(
            name='TrainingCourseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='training/courses/attachments/')),
                ('visibility', models.CharField(choices=[('ALL', 'All learners'), ('TRAINING_ONLY', 'Training team only'), ('MANAGERS_ONLY', 'Managers only')], default='ALL', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='training.trainingcourse')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_training_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('module_type', models.CharField(choices=[('INSTRUCTOR_LED', 'Instructor Led'), ('SELF_PACED', 'Self Paced'), ('BLENDED', 'Blended')], default='SELF_PACED', max_length=20)),
                ('publish_start_date', models.DateField()),
                ('publish_end_date', models.DateField(blank=True, null=True)),
                ('supporting_attachment', models.FileField(blank=True, null=True, upload_to='training/modules/attachments/')),
                ('capacity_min', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity_max', models.PositiveIntegerField(blank=True, null=True)),
                ('waitlist_enabled', models.BooleanField(default=False)),
                ('cme_cne_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('validity_years', models.PositiveIntegerField(default=1)),
                ('approval_required', models.BooleanField(default=False)),
                ('is_sequential', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_training_modules', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.trainingcourse')),
                ('training_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='training.trainingcategory')),
            ],
            options={'ordering': ['order_index', 'title']},
        ),
        migrations.CreateModel(
            name='TrainingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('section_type', models.CharField(choices=[('READING', 'Reading Material'), ('ASSESSMENT', 'Assessment'), ('FEEDBACK', 'Feedback'), ('RECORDED', 'Recorded Session')], max_length=20)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('completion_mode', models.CharField(choices=[('PER_SECTION', 'Per Section'), ('PER_ACTIVITY', 'Per Sub-Activity')], default='PER_SECTION', max_length=20)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='training.trainingmodule')),
            ],
            options={'ordering': ['sequence_order', 'title']},
        ),
        migrations.CreateModel(
            name='TrainingSubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('PDF', 'PDF'), ('PPT', 'PowerPoint'), ('SCORM', 'SCORM'), ('VIDEO', 'Video'), ('ASSESSMENT', 'Assessment'), ('COVER', 'Cover Page')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='training/subactivities/')),
                ('external_url', models.URLField(blank=True)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_subactivities', to='training.trainingcontent')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_activities', to='training.trainingsection')),
            ],
            options={'ordering': ['sequence_order', 'title']},
        ),
        migrations.CreateModel(
            name='TrainingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_allowed', models.PositiveIntegerField(default=1)),
                ('passing_score', models.PositiveIntegerField(default=0)),
                ('scoring_mode', models.CharField(choices=[('AVERAGE', 'Average'), ('SUM', 'Sum')], default='SUM', max_length=10)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('is_feedback', models.BooleanField(default=False)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='training.trainingsection')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_paths', to='core.businessunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='TrainingLearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_links', to='training.trainingcourse')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_courses', to='training.traininglearningpath')),
            ],
            options={'ordering': ['sequence_order'], 'unique_together': {('learning_path', 'course')}},
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assignment_type', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('MANDATORY', 'Mandatory'), ('VOLUNTARY', 'Voluntary')], default='RECOMMENDED', max_length=20)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('learner_note', models.TextField(blank=True)),
                ('notify_schema', models.JSONField(blank=True, default=dict)),
                ('allow_retake', models.BooleanField(default=False)),
                ('exempt_if_completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_assignments', to='core.department')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_assignments', to='core.businessunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-start_date']},
        ),
        migrations.CreateModel(
            name='TrainingAssignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training.trainingassignment')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_items', to='training.trainingcourse')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_items', to='training.traininglearningpath')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXEMPTED', 'Exempted')], default='ASSIGNED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('assignment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.trainingassignmentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-id'], 'unique_together': {('assignment_item', 'user')}},
        ),
        migrations.CreateModel(
            name='TrainingEmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_profiles', to='core.businessunit')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_profiles', to='core.department')),
                ('line_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_training_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['user_id'], 'unique_together': {('business_unit', 'user')}},
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='mandatory_departments',
            field=models.ManyToManyField(blank=True, related_name='mandatory_training_courses', to='core.department'),
        ),
    ]
